pipeline:
  name: Build Harness
  identifier: Build_Harness_1700465693829
  projectIdentifier: PytDemoproj
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and push docker iamge
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: pytconnectornew
                    repo: kashsura/pyt-flask
                    tags:
                      - latest
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
    - stage:
        name: pyt-deploy
        identifier: pytdeploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: pytservice
          environment:
            environmentRef: pytenvi
            deployToAll: false
            infrastructureDefinitions:
              - identifier: pytenviinfra
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1700273705190
        repoName: kashsura/Harness
        build: <+input>
