pipeline:
  name: Build Harness
  identifier: Build_Harness_1700465693829
  projectIdentifier: PytDemoproj
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and push docker iamge
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: pytconnectornew
                    repo: kashsura/pyt-flask
                    tags:
                      - latest
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1700273705190
        repoName: kashsura/Harness
        build: <+input>
