pipeline:
  name: Build Python-Harness
  identifier: Build_kashsura_Python_Harness_1700546167468
  projectIdentifier: PythonHarnessProject
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerImage
                  identifier: BuildAndPushDockerImage
                  spec:
                    connectorRef: dockerhub_connector
                    repo: kashsura/pyt-flask
                    tags:
                      - latest
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1700273705190
        repoName: kashsura/Python-Harness
        build: <+input>
